version: 0.2

env:
  shell: bash
  variables:
    PROJECT_DIR: "clients/flutter"
    FLUTTER_CHANNEL: "stable"
    FLUTTER_VERSION: "3.24.3"

cache:
  paths:
    - /root/.pub-cache/**

phases:
  install:
    commands:
      - set -euo pipefail
      - echo "=== Harden apt sources and update with retries ==="
      - sed -i '/jammy-backports/s/^/# /' /etc/apt/sources.list || true
      - n=0; until apt-get update -y; do n=$((n+1)); [ $n -ge 5 ] && { echo "apt-get update failed after $n tries"; exit 1; }; echo "retry $n: apt-get update"; sleep $((5*n)); done
      - apt-get install -y curl git unzip xz-utils libglu1-mesa
      - echo "=== Fetch Flutter SDK ${FLUTTER_VERSION} (${FLUTTER_CHANNEL}) ==="
      - curl -L -o "flutter_linux_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.tar.xz" "https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.tar.xz"
      - tar -xf "flutter_linux_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.tar.xz"
      - export PATH="$PWD/flutter/bin:$PATH"
      - git config --global --add safe.directory "$PWD/flutter"
      - flutter --version
      - flutter config --enable-web
      - echo "=== Check project and ensure web platform exists ==="
      - ls -la "${PROJECT_DIR}"
      - test -f "${PROJECT_DIR}/pubspec.yaml" || { echo "ERROR: No pubspec.yaml in ${PROJECT_DIR}"; exit 1; }
      - test -f "${PROJECT_DIR}/web/index.html" || (cd "${PROJECT_DIR}" && flutter create --platforms=web .)
      - (cd "${PROJECT_DIR}" && flutter pub get)

  build:
    commands:
      - set -euo pipefail
      - echo "=== Build Flutter WEB (release) ==="
      - (cd "${PROJECT_DIR}" && flutter build web --release --verbose)

  post_build:
    commands:
      - echo "=== Verify artifacts ==="
      - test -f "${PROJECT_DIR}/build/web/index.html" || { echo "ERROR: web build missing index.html"; exit 2; }
      - du -sh "${PROJECT_DIR}/build/web" || true

artifacts:
  base-directory: clients/flutter/build/web
  files:
    - '**/*'
