version: 0.2

env:
  variables:
    APP_DIR: clients/flutter   # <-- change if your app lives elsewhere

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y curl git unzip xz-utils libglu1-mesa
      - curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz
      - tar -xf flutter_linux_3.24.3-stable.tar.xz
      - export PATH="$PWD/flutter/bin:$PATH"
      - git config --global --add safe.directory "$PWD/flutter"
      - flutter --version
      - flutter config --enable-web
      - ls -la "$APP_DIR"
      - test -f "$APP_DIR/pubspec.yaml" || (echo "ERROR: No pubspec.yaml in $APP_DIR" && exit 1)
      # 👇 THIS is the missing piece — creates web/ (index.html, manifest, icons) if absent
      - test -f "$APP_DIR/web/index.html" || (cd "$APP_DIR" && flutter create --platforms=web .)
      - (cd "$APP_DIR" && flutter pub get)

  build:
    commands:
      - (cd "$APP_DIR" && flutter build web --release)

artifacts:
  base-directory: $APP_DIR/build/web
  files:
    - '**/*'
