version: 0.2

env:
  variables:
    CI: "true"

cache:
  paths:
    - /root/.pub-cache
    - flutter/bin/cache

phases:
  install:
    commands:
      - set -e
      - echo "=== Install base packages ==="
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update -y
      - apt-get install -y curl git unzip xz-utils libglu1-mesa
      - echo "=== Download & setup Flutter SDK (latest stable via git) ==="
      - git clone -b stable https://github.com/flutter/flutter.git
      - export PATH="$PWD/flutter/bin:$PATH"
      - git config --global --add safe.directory "$PWD/flutter"
      - flutter --disable-analytics || true
      - flutter config --enable-web || true
      - flutter --version
      - dart --version

      - echo "=== Locate Flutter app directory ==="
      - |
        if [ -f clients/flutter/pubspec.yaml ]; then
          APP_DIR="clients/flutter"
        elif [ -f pubspec.yaml ]; then
          APP_DIR="."
        else
          echo "ERROR: Could not find pubspec.yaml in expected locations."
          find . -maxdepth 3 -type f -name pubspec.yaml -print
          exit 1
        fi
        echo "$APP_DIR" > .appdir
        echo "Using APP_DIR=$APP_DIR"

      - echo "=== Fetch project dependencies ==="
      - APP_DIR="$(cat .appdir)"
      - (cd "$APP_DIR" && flutter pub get)

  pre_build:
    commands:
      - echo "=== Pre-build complete ==="

  build:
    commands:
      - set -e
      - echo "=== Run unit/widget tests (if present) ==="
      - APP_DIR="$(cat .appdir)"
      - |
        if [ -d "$APP_DIR/test" ]; then
          (cd "$APP_DIR" && flutter test --coverage)
        else
          echo "No test directory at $APP_DIR/test — skipping tests"
          (cd "$APP_DIR" && flutter analyze --no-fatal-infos --no-fatal-warnings) || true
        fi

      - echo "=== Build web bundle ==="
      - (cd "$APP_DIR" && flutter build web --release)

artifacts:
  files:
    - '**/*'
  base-directory: clients/flutter/build/web
