version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - set -euo pipefail
      - echo "=== Download Flutter SDK ==="
      - curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz
      - tar -xf flutter_linux_3.24.3-stable.tar.xz
      - export PATH="$PWD/flutter/bin:$PATH"
      - git config --global --add safe.directory "$PWD/flutter"
      - flutter --version
      - flutter config --enable-web
      - echo "=== Ensure web platform exists + get deps ==="
      - test -f clients/flutter/pubspec.yaml || { echo "ERROR: missing pubspec.yaml under clients/flutter"; exit 1; }
      - test -f clients/flutter/web/index.html || (cd clients/flutter && flutter create --platforms=web .)
      - cd clients/flutter && flutter pub get && cd -

  build:
    commands:
      - echo "=== Build Flutter web (release) ==="
      - cd clients/flutter && flutter build web --release && cd -

artifacts:
  base-directory: clients/flutter/build/web
  files:
    - '**/*'
