version: 0.2

env:
  variables:
    FLUTTER_SDK_URL: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz

phases:
  install:
    commands:
      - set -e
      - echo "=== Install base packages ==="
      - apt-get update -y
      - apt-get install -y curl git unzip xz-utils libglu1-mesa
      - echo "=== Download & setup Flutter SDK ==="
      - curl -L -o flutter.tar.xz "$FLUTTER_SDK_URL"
      - tar -xf flutter.tar.xz
      - export PATH="$PWD/flutter/bin:$PATH"
      - git config --global --add safe.directory "$PWD/flutter"
      - flutter --version || true
      - flutter config --enable-web || true
      - echo "=== Fetch project dependencies ==="
      - cd clients/flutter
      - flutter pub get

  build:
    commands:
      - set -e
      - echo "=== Run unit/widget tests ==="
      - cd clients/flutter
      - flutter test --coverage
      # For web tests with a headless browser, optionally:
      # - apt-get install -y chromium-browser || apt-get install -y chromium || true
      # - CHROME_EXECUTABLE=$(command -v chromium-browser || command -v chromium || echo "")
      # - if [ -n "$CHROME_EXECUTABLE" ]; then flutter test --platform=chrome --headless --coverage; fi

artifacts:
  files:
    - clients/flutter/coverage/**/*
  discard-paths: no
